"""
Django settings for reprocreate project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import datetime
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-5^#+#^h44vyy$d$0-9-+_c**=xz$g!ilvh7*c(@zeykpzk_*o_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '*', 
    '127.0.0.1', 
    'localhost', 
    '.vercel.app', 
    'https://reprocreate-africa.onrender.com',
    'reprocreate-africa.onrender.com',
    'http://localhost:3003', 
    'https://localhost:3003', 
    'http://127.0.0.1:3003',
    'http://localhost:3003/',
    'https://localhost:3003/',
    'https://127.0.0.1:3003',
    'http://localhost:3000', 
    'https://localhost:3000', 
    'http://127.0.0.1:3000',
    'http://localhost:3000/',
    'https://localhost:3000/',
    'https://127.0.0.1:3000',
    ]

AUTH_USER_MODEL = 'authentication.User'
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework_simplejwt.token_blacklist',
    'rest_framework_simplejwt',
    'rest_framework',
    'corsheaders',
    'store',
    'central',
    'users',
    'authentication',
    # 'django_seed',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'reprocreate.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'reprocreate.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'NON_FIELD_ERRORS_KEY': 'error',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': datetime.timedelta(minutes=50),
    'REFRESH_TOKEN_LIFETIME': datetime.timedelta(days=1),
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS =  BASE_DIR / 'assests',

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# MEDIA_URL = '/images/'




# MEDIA_ROOT = BASE_DIR / 'static/images'
# STATIC_ROOT = BASE_DIR / 'staticfiles'

CORS_ORIGIN_ALLOW_ALL = True

CORS_ORIGIN_WHITELIST = [   
    'http://localhost:3003', 
    'https://localhost:3003', 
    'http://127.0.0.1:3003',
    'https://127.0.0.1:3003',
    'http://localhost:3000', 
    'https://localhost:3000', 
    'http://127.0.0.1:3000',
    'https://127.0.0.1:3000',
    # Add other allowed origins here
]
CORS_ALLOWED_ORIGINS = [   
    'http://localhost:3003', 
    'https://localhost:3003', 
    'http://127.0.0.1:3003',
    'https://127.0.0.1:3003',
    'http://localhost:3000', 
    'https://localhost:3000', 
    'http://127.0.0.1:3000',
    'https://127.0.0.1:3000',
]
# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'aderibigbeawwal@gmail.com'
DEFAULT_FROM_EMAIL = 'aderibigbeawwal@gmail.com'
EMAIL_PORT = 465
EMAIL_HOST_PASSWORD = 'ykovzwdfouduyija'
EMAIL_USE_SSL = True
EMAIL_USE_TLS = False